function rest(path) {
  return {
    createPath: path,
    createMethod: 'POST',
    updatePath: path,
    updateMethod: 'PUT',
    deletePath: (id) => `${path}/${id}`,
  }
}

function store(path) {
  return {
    createPath: `${path}/store`,
    createMethod: 'POST',
    updatePath: `${path}/store`,
    updateMethod: 'POST',
    deletePath: (id) => `${path}/${id}/delete`,
  }
}

export const MASTER_PAGES = [
  {
    slug: 'departments',
    title: 'Departments',
    copy: 'Organisation departments.',
    path: '/backend/api/master/department',
    fields: ['name', 'groupEmail', 'parentId', 'headId', 'id'],
    form: [
      { name: 'name', label: 'Name', required: true },
      { name: 'groupEmail', label: 'Group email', type: 'email' },
      { name: 'parentId', label: 'Parent ID', type: 'number' },
      { name: 'headId', label: 'Head user ID', type: 'number' },
    ],
    ...rest('/backend/api/master/department'),
  },
  {
    slug: 'job-titles',
    title: 'Job titles',
    copy: 'Roles and designations.',
    path: '/backend/api/master/job-titles',
    fields: ['name', 'description', 'id'],
    form: [
      { name: 'name', label: 'Name', required: true },
      { name: 'description', label: 'Description' },
    ],
    ...rest('/backend/api/master/job-titles'),
  },
  {
    slug: 'locations',
    title: 'Office locations',
    copy: 'Workplaces and addresses.',
    path: '/backend/api/master/office-location',
    fields: ['name', 'id'],
    form: [{ name: 'name', label: 'Location name', required: true }],
    ...rest('/backend/api/master/office-location'),
  },
  {
    slug: 'shifts',
    title: 'Shifts',
    copy: 'Shift codes and timings.',
    path: '/backend/api/master/shifts',
    fields: ['name', 'code', 'isFlexible', 'id'],
    form: [
      { name: 'name', label: 'Name', required: true },
      { name: 'code', label: 'Code', required: true },
      { name: 'isFlexible', label: 'Flexible', type: 'checkbox' },
      { name: 'start_time_buffer', label: 'Start buffer (min)', type: 'number', value: 15 },
      { name: 'end_time_buffer', label: 'End buffer (min)', type: 'number', value: 15 },
      { name: 'halfDayInTime', label: 'Half-day in time', value: '13:00' },
    ],
    ...rest('/backend/api/master/shifts'),
  },
  {
    slug: 'weekly-off',
    title: 'Weekly off groups',
    copy: 'Rest-day rules.',
    path: '/backend/api/master/weekly-off-groups',
    fields: ['name', 'activeStatus', 'id'],
    form: [
      { name: 'name', label: 'Name', required: true },
      { name: 'activeStatus', label: 'Active status', value: '1' },
    ],
    ...rest('/backend/api/master/weekly-off-groups'),
  },
  {
    slug: 'holidays',
    title: 'Holiday master',
    copy: 'Holiday calendar records.',
    path: '/backend/api/master/holidays',
    fields: ['holidayName', 'holidayDate', 'year', 'isOptional', 'id'],
    form: [
      { name: 'holidayName', label: 'Holiday name', required: true },
      { name: 'holidayDate', label: 'Date', type: 'date', required: true },
      { name: 'year', label: 'Year', value: '2026' },
      { name: 'isOptional', label: 'Optional', type: 'checkbox' },
    ],
    ...rest('/backend/api/master/holidays'),
  },
  {
    slug: 'pay-grades',
    title: 'Pay grades',
    copy: 'Salary grade bands.',
    path: '/backend/api/master/pay-grades',
    fields: ['name', 'description', 'minAmount', 'maxAmount', 'id'],
    form: [
      { name: 'name', label: 'Name', required: true },
      { name: 'description', label: 'Description' },
      { name: 'minAmount', label: 'Min amount', type: 'number' },
      { name: 'maxAmount', label: 'Max amount', type: 'number' },
    ],
    ...rest('/backend/api/master/pay-grades'),
  },
  {
    slug: 'ip-address',
    title: 'IP address',
    copy: 'Office network access rules.',
    path: '/backend/api/master/ip-address',
    fields: ['ipAddress', 'anyIpAccess', 'fromDate', 'toDate', 'id'],
    form: [
      { name: 'ipAddress', label: 'IP address', required: true },
      { name: 'anyIpAccess', label: 'Any IP access', type: 'checkbox' },
      { name: 'fromDate', label: 'From', type: 'date' },
      { name: 'toDate', label: 'To', type: 'date' },
    ],
    ...rest('/backend/api/master/ip-address'),
  },
  {
    slug: 'regularization-policy',
    title: 'Regularization policy',
    copy: 'Correction limits and amounts.',
    path: '/backend/api/master/regularization-policy',
    fields: ['name', 'minCount', 'maxCount', 'amount', 'id'],
    form: [
      { name: 'name', label: 'Name', required: true },
      { name: 'minCount', label: 'Min count', type: 'number', required: true },
      { name: 'maxCount', label: 'Max count', type: 'number', required: true },
      { name: 'amount', label: 'Amount', type: 'number' },
    ],
    ...rest('/backend/api/master/regularization-policy'),
  },
  {
    slug: 'penalty-policy',
    title: 'Penalty policy',
    copy: 'Late and missing-swipe rules.',
    path: '/backend/api/master/penalty-policy',
    fields: ['name', 'id'],
    form: [{ name: 'name', label: 'Name', required: true }],
    ...rest('/backend/api/master/penalty-policy'),
  },
  {
    slug: 'probation-policy',
    title: 'Probation policy',
    copy: 'Probation length and status.',
    path: '/backend/api/master/probation-policy',
    fields: ['name', 'duration', 'duration_unit', 'active_status', 'id'],
    form: [
      { name: 'name', label: 'Name', required: true },
      { name: 'description', label: 'Description' },
      { name: 'duration', label: 'Duration', type: 'number', required: true, value: 6 },
      { name: 'duration_unit', label: 'Unit', value: 'months' },
      { name: 'active_status', label: 'Active', type: 'checkbox', value: true },
    ],
    ...rest('/backend/api/master/probation-policy'),
  },
  {
    slug: 'notice-period',
    title: 'Notice period',
    copy: 'Exit notice durations.',
    path: '/backend/api/master/notice-period',
    fields: ['title', 'name', 'duration', 'duration_unit', 'active_status', 'id'],
    form: [
      { name: 'title', label: 'Title', required: true },
      { name: 'duration', label: 'Duration', type: 'number', required: true, value: 30 },
      { name: 'duration_unit', label: 'Unit', value: 'days' },
      { name: 'active_status', label: 'Active', type: 'checkbox', value: true },
    ],
    ...rest('/backend/api/master/notice-period'),
  },
  {
    slug: 'legal-entities',
    title: 'Legal entities',
    copy: 'Registered entities.',
    path: '/backend/api/master/legal-entities',
    fields: ['name', 'description', 'id'],
    form: [
      { name: 'name', label: 'Name', required: true },
      { name: 'description', label: 'Description' },
    ],
    ...rest('/backend/api/master/legal-entities'),
  },
  {
    slug: 'business-units',
    title: 'Business units',
    copy: 'Units under the organisation.',
    path: '/backend/api/organization/business-units',
    fields: ['name', 'description', 'organizationId', 'id'],
    form: [
      { name: 'name', label: 'Name', required: true },
      { name: 'description', label: 'Description' },
      { name: 'organizationId', label: 'Organisation ID', value: '1' },
    ],
    ...rest('/backend/api/organization/business-units'),
  },
  {
    slug: 'leave-type',
    title: 'Leave types',
    copy: 'Casual, unpaid and other types.',
    path: '/backend/api/master/leave-settings/leave-type',
    fields: ['name', 'allowHalfDay', 'id'],
    form: [
      { name: 'name', label: 'Name', required: true },
      { name: 'allowHalfDay', label: 'Allow half day', type: 'checkbox', value: true },
    ],
    ...store('/backend/api/master/leave-settings/leave-type'),
  },
  {
    slug: 'leave-plan',
    title: 'Leave plans',
    copy: 'Plans assigned to people.',
    path: '/backend/api/master/leave-settings/leave-plan',
    fields: ['name', 'is_active', 'id'],
    form: [
      { name: 'name', label: 'Name', required: true },
      { name: 'is_active', label: 'Active', type: 'checkbox', value: true },
    ],
    ...store('/backend/api/master/leave-settings/leave-plan'),
  },
  {
    slug: 'attendance-lock',
    title: 'Attendance lock',
    copy: 'Month lock date from general settings.',
    path: '/backend/api/master/general-settings/attendance-lock',
    record: true,
    fields: ['attendance_lock_date', 'lockDate', 'date'],
    form: [{ name: 'attendance_lock_date', label: 'Lock date', type: 'date', required: true }],
    createPath: null,
    updatePath: '/backend/api/master/general-settings/attendance-lock/save',
    updateMethod: 'POST',
    deletePath: null,
  },
  {
    slug: 'attendance-unlocks',
    title: 'Attendance unlocks',
    copy: 'Temporary unlocks. This API returned 403 for some roles.',
    path: `/backend/api/master/attendance-unlocks?month=${new Date().toISOString().slice(0, 7)}-01&page=1`,
    fields: ['user_id', 'from_date', 'to_date', 'expires_in_hours', 'id'],
    form: [
      { name: 'user_id', label: 'User ID', type: 'number', required: true },
      { name: 'from_date', label: 'From', type: 'date', required: true },
      { name: 'to_date', label: 'To', type: 'date', required: true },
      { name: 'expires_in_hours', label: 'Expires in hours', type: 'number', value: 24 },
      { name: 'reason', label: 'Reason', required: true },
    ],
    createPath: '/backend/api/master/attendance-unlocks/store',
    createMethod: 'POST',
    updatePath: (id) => `/backend/api/master/attendance-unlocks/${id}/update`,
    updateMethod: 'PUT',
    deletePath: (id) => `/backend/api/master/attendance-unlocks/${id}/delete`,
  },
  {
    slug: 'penalty-status',
    title: 'Penalty status',
    copy: 'General penalty setting. Read-only in the recovered client.',
    path: '/backend/api/master/general-settings/penalty-status',
    record: true,
    fields: ['status', 'activeStatus', 'enabled'],
    form: [],
  },
]

export function getMaster(slug) {
  return MASTER_PAGES.find((item) => item.slug === slug)
}
